<a href="https://colab.research.google.com/github/turjo997/Neural-Network-And-Deep-Learning-/blob/main/Copy_of_Lab_01_Introduction_to_NumPy_%26_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center">
<img src="https://drive.google.com/uc?id=1JOzNG8Sf9rXQ_nHqlzOvzOnpr4iSIkmc" width="250">

<img src="https://drive.google.com/uc?id=1SctzfeQJDdGN2eMRQhJEoQWWO9rovrWh" width="300">
</div>


## Numpy

[Numpy](https://numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. To use Numpy, we first need to import the numpy package as `import numpy as np`

In [1]:
import numpy as np

### Arrays

A numpy array is a grid of values, **all of the same type**, and is indexed by a tuple of nonnegative integers. **The number of dimensions is the rank of the array**; the shape of an array is a tuple of integers giving the size of the array along each dimension. We can initialize numpy arrays from nested Python lists, and access elements using square brackets:



In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
a = np.array([1,2,3])
print(type(a) , a.shape , a[0] , a[1] , a[2])
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[1 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = np.array([[1,2,3,4] , [4,5,6,5] , [7,5,8,9]])
print(b)
print(type(b) , b.shape , b[0] , b[1])

[[1 2 3 4]
 [4 5 6 5]
 [7 5 8 9]]
<class 'numpy.ndarray'> (3, 4) [1 2 3 4] [4 5 6 5]


In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [ ]:
c = np.array([[ 
               [1,2,3,4],
               [5,6,7,8],
               [9,10,11,12], 
               [1,1,1,1]   
]])
print(c)
print(c.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [ 1  1  1  1]]]
(1, 4, 4)


Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
a = np.zeros((3,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [ ]:
c = np.full((3,4) , 1)
print(c)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.20955718 0.93061151]
 [0.00104743 0.6772676 ]]


In [ ]:
d = np.random.random((3,4))
print(d)

[[0.00953708 0.94803274 0.90088508 0.97178612]
 [0.49005467 0.06160121 0.00906252 0.96390768]
 [0.51129131 0.32755198 0.91456239 0.45727397]]


In [ ]:
image = np.array([[[ 0.67826139, 0.29380381 , 2],
 [ 0.90714982, 0.52835647 , 1],
 [ 0.4215251 , 0.45017551 , 2]],
 [[ 0.92814219, 0.96677647 , 3],
 [ 0.85304703, 0.52351845 , 1],
 [ 0.19981397, 0.27417313 , 2]],
 [[ 0.60659855, 0.0053316 , 5],
 [ 0.10820313, 0.49978937 , 3],
 [ 0.34144279, 0.94630077 , 4]]])
print(image)
print(image.shape)
print("transpose\n", image.T)

[[[0.67826139 0.29380381 2.        ]
  [0.90714982 0.52835647 1.        ]
  [0.4215251  0.45017551 2.        ]]

 [[0.92814219 0.96677647 3.        ]
  [0.85304703 0.52351845 1.        ]
  [0.19981397 0.27417313 2.        ]]

 [[0.60659855 0.0053316  5.        ]
  [0.10820313 0.49978937 3.        ]
  [0.34144279 0.94630077 4.        ]]]
(3, 3, 3)
transpose
 [[[0.67826139 0.92814219 0.60659855]
  [0.90714982 0.85304703 0.10820313]
  [0.4215251  0.19981397 0.34144279]]

 [[0.29380381 0.96677647 0.0053316 ]
  [0.52835647 0.52351845 0.49978937]
  [0.45017551 0.27417313 0.94630077]]

 [[2.         3.         5.        ]
  [1.         1.         3.        ]
  [2.         2.         4.        ]]]


### Datatypes

**Every numpy array is a grid of elements of the same type.** Numpy provides a large set of numeric datatypes that you can use to construct arrays. **Numpy tries to guess a datatype when you create an array**, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


## Array math

**Basic mathematical functions operate elementwise on arrays**, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
a = np.array([[1,2,3] , [4,5,6]] , dtype=np.float64)
b = np.array([[10,20,30] , [4,5,6]] , dtype=np.float64)
print(a+b)
print(np.add(a,b))

[[11. 22. 33.]
 [ 8. 10. 12.]]
[[11. 22. 33.]
 [ 8. 10. 12.]]


In [ ]:
print(x- y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))
print(a-b)
print(np.subtract(a,b))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ -9. -18. -27.]
 [  0.   0.   0.]]
[[ -9. -18. -27.]
 [  0.   0.   0.]]


In [ ]:
 # Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


 ## **Important Note**
 
 `*` is elementwise multiplication, not matrix multiplication. **We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.** dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

x1 = np.array([[1,1],[2,3]])
y1 = np.array([[1,1],[1,1]])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
print(x.dot(y))
print(np.dot(x,y))
print(np.dot(x1,y1))

219
219
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[2 2]
 [5 5]]


**You can also use the @ operator which is equivalent to numpy's dot operator.**

In [ ]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


In [ ]:
import numpy as np

# example of numpy array
x = np.array([1, 2, 3])
print(x)

[1 2 3]


If $x$ is a vector, then a Python operation such as $s = x + 3$ or $s = \frac{1}{x}$ will output s as a vector of the same size as x.

In [ ]:
# example of vector operation
x = np.array([1, 2, 3])
print (x + 3)
print(x*3)

[4 5 6]
[3 6 9]


In fact, if $ x = (x_1, x_2, ..., x_n)$ is a row vector then $np.exp(x)$ will apply the exponential function to every element of x. The output will thus be: $np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})$

In [ ]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


Any time you need more info on a numpy function, we encourage you to look at [the official documentation](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.exp.html). 

## What is Pytorch? 

[PyTorch](https://pytorch.org/) is a python package built by **Facebook AI Research (FAIR)** that provides two high-level features:
- Tensor computation (like numpy) with strong GPU acceleration
- Deep Neural Networks built on a tape-based autograd (*Automatic Gradient Calculation*) system

## Why Pytorch? 
- **More Pythonic** 
    - Flexible
    - Intuitive and cleaner code
    - Easy to learn & debug
    - Dynamic Computation Graph (*network behavior can be changed programmatically at runtime*)

- **More Neural Networkic**
    - Write code as the network works
    - forward/backward



## Checking PyTorch version

In [ ]:
import torch

print(torch.__version__)

1.11.0+cu113


## Introduction to Tensors

A **PyTorch Tensor** is basically the same as a numpy array: it does not know anything about deep learning or computational graphs or gradients, and is just a generic **n-dimensional array** to be used for arbitrary **numeric computation**.

The biggest difference between a numpy array and a PyTorch Tensor is that a **PyTorch Tensor can run on either CPU or GPU**. To run operations on the GPU, **just cast the Tensor to a cuda datatype**.


A scalar is **zero-order tensor** or rank zero tensor. A vector is a **one-dimensional** or first order tensor, and a matrix is a **two-dimensional** or second order tensor. 



<div align="center">
<img src="https://drive.google.com/uc?id=1pka-LVyrq_7r0sCm59cvOQofEYAcnO4r" width="550">
</div>

<div align="center">
<img src="https://drive.google.com/uc?id=1zHT5CGzIgpe1aLkdawrllTMn74nYVeAp" width="550">
</div>



A [torch.Tensor](https://pytorch.org/docs/stable/tensors.html) is a **multi-dimensional matrix** containing elements of a **single data type**.

`torch.Tensor` is an alias for the default tensor type (`torch.FloatTensor`).

In [ ]:
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [ ]:
a = torch.tensor([1,2,3])
print(a)

tensor([1, 2, 3])


In [ ]:
x = torch.rand(5, 4)
print(x)

tensor([[0.0301, 0.5736, 0.3542, 0.9704],
        [0.2157, 0.6605, 0.4866, 0.4369],
        [0.8935, 0.3767, 0.0434, 0.3960],
        [0.8388, 0.7885, 0.0598, 0.7739],
        [0.6928, 0.9475, 0.0510, 0.8083]])


In [ ]:
# Converting numpy arrays to tensors
import numpy as np
print(torch.tensor(np.array([[1, 2, 3], [4, 5, 6]])))
print(torch.tensor(np.array([1,2,3])))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])


In [ ]:
# Converting numpy arrays to tensors
np_values = np.array([[1, 2, 3], [4, 5, 6]])

tensor_values = torch.from_numpy(np_values)

print (tensor_values)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# A tensor of specific data type can be constructed by passing a torch.dtype

torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
torch.ones([3,3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[0][2])

# Modify a certain element
x[0][1] = 8
print(x)

tensor(3)
tensor([[1, 8, 3],
        [4, 5, 6]])


In [ ]:
# Use torch.Tensor.item() to get a Python number from a tensor containing a single value

x = torch.tensor([[1]])
print (x)

print(x.item())

x = torch.tensor(2.5)

print(x.item())

tensor([[1]])
1
2.5


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [ ]:
# Tensor addition & subtraction
x = torch.rand(5, 3)
y = torch.rand(5, 3)

print(x)
print(y)

print(x + y)
print(x - y)ma

tensor([[0.9365, 0.2817, 0.4693],
        [0.8490, 0.9531, 0.6792],
        [0.9359, 0.9665, 0.4676],
        [0.5986, 0.0448, 0.6475],
        [0.2194, 0.6032, 0.9803]])
tensor([[0.3623, 0.1171, 0.7549],
        [0.3590, 0.3777, 0.6061],
        [0.4448, 0.9306, 0.4088],
        [0.2944, 0.6492, 0.9925],
        [0.0678, 0.0946, 0.6485]])
tensor([[1.2988, 0.3988, 1.2242],
        [1.2079, 1.3308, 1.2853],
        [1.3807, 1.8971, 0.8764],
        [0.8930, 0.6940, 1.6400],
        [0.2872, 0.6978, 1.6288]])
tensor([[ 0.5743,  0.1646, -0.2856],
        [ 0.4900,  0.5754,  0.0730],
        [ 0.4910,  0.0359,  0.0589],
        [ 0.3043, -0.6045, -0.3450],
        [ 0.1516,  0.5086,  0.3319]])


In [ ]:
# Syntax 2 for Tensor addition & subtraction in PyTorch
print(torch.add(x, y))
print(torch.sub(x, y))

tensor([[0.7682, 1.6622, 1.5926],
        [0.4518, 1.5748, 1.0312],
        [1.0234, 1.6341, 1.0088],
        [0.8739, 0.4333, 0.6369],
        [0.9130, 1.5716, 1.0837]])
tensor([[-0.5354,  0.1980,  0.0660],
        [-0.0280, -0.3690,  0.7516],
        [ 0.5595,  0.3053,  0.5034],
        [-0.2324,  0.2065,  0.4731],
        [ 0.7916, -0.1611,  0.7863]])


In [ ]:
# Tensor Product & Transpose

mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)

print(mat1)
print(mat2)

print(torch.mm(mat1, mat2))

print(mat1.t())

tensor([[-0.7973,  0.1136,  1.8127],
        [ 0.7322,  0.3296,  0.2570]])
tensor([[-0.8258,  1.0713, -0.3133],
        [-1.1580, -0.9988, -0.5260],
        [-0.8536,  0.4212,  1.0959]])
tensor([[-1.0205, -0.2040,  2.1767],
        [-1.2057,  0.5636, -0.1211]])
tensor([[-0.7973,  0.7322],
        [ 0.1136,  0.3296],
        [ 1.8127,  0.2570]])


In [ ]:
# Elementwise multiplication
t = torch.Tensor([[1, 2], [3, 4]])
t.mul(t)

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [ ]:
# Shape, dimensions, and datatype of a tensor object

x = torch.rand(5, 3)

print('Tensor shape:', x.shape)   # t.size() gives the same
print('Number of dimensions:', x.dim())
print('Tensor type:', x.type())   # there are other types

Tensor shape: torch.Size([5, 3])
Number of dimensions: 2
Tensor type: torch.FloatTensor


In [ ]:
# Slicing
t = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Every row, only the last column
print(t[:, -1])

# First 2 rows, all columns
print(t[:2, :])

# Lower right most corner
print(t[-1:, -1:])

tensor([3., 6., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[9.]])


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
print(a[1:4])
print(a[1:4:2])
print(a[:])
print(a[1:])
print(a[:5])
print(a[0::2])

[2 3 4]
[2 4]
[1 2 3 4 5]
[2 3 4 5]
[1 2 3 4 5]
[1 3 5]


In [ ]:
print(a[-2:-1])
print(a[-5:-1])
print(a[-4:-1])
print(a[-4:-1:2])
print(a[-5:])
print(a[-1:-4])
print(a[:-3])
print(a[-5:-5])
print(a[-5:-4])
print(a[-1:-1])

[4]
[1 2 3 4]
[2 3 4]
[2 4]
[1 2 3 4 5]
[]
[1 2]
[]
[1]
[]


In [ ]:
a = np.array([[1,2] , [3,4] , [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(a[1: , 1:])
print(a[: , :])

[[4]
 [6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([[1,2,3,4] , [5,6,7,8] , [20,30,40,50]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [20 30 40 50]]


In [ ]:
print(a[1: , 1:])

[[ 6  7  8]
 [30 40 50]]


In [ ]:
print(a[:: , ::2])

[[ 1  3]
 [ 5  7]
 [20 40]]


In [ ]:
print(a[1: , 0:2])
print(a[0:2 , 1:3])

[[ 5  6]
 [20 30]]
[[2 3]
 [6 7]]


In [ ]:
print(a[::2 , ::2])

[[[ 1  2  3  4]
  [ 9 10 11 12]]]


In [ ]:
a = np.array([
              [[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              
              [[13,14,15,16],
              [17,18,19,20],
              [21,22,23,24]]])
print(a)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
print(a[:,:,:1])

[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]


In [ ]:
print(a[1: , 1: , :1])

[[[17]
  [21]]]


In [ ]:
arr = np.array([[ [1,2,3] , [4,5,6]] , [[7,8,9] , [10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr[ 1: , 0: , 1: ])
print(arr[ 1: , : , 1: ])

[[[ 8  9]
  [11 12]]]
[[[ 8  9]
  [11 12]]]


In [ ]:
print(arr[0:1 , : , :2])
print(arr[0:1 , : , ::2])
print(arr[: , : , :2])


[[[1 2]
  [4 5]]]
[[[1 3]
  [4 6]]]
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [2]:
a= np.array([
             [[1,2,3,4] , 
              [5,6,7,8] , 
              [9,10,11,12]] , 

             [[13,14,15,16],
             [19,20,21,22],
             [23,24,25,25]]])

print(a)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [19 20 21 22]
  [23 24 25 25]]]


In [3]:
print(a[ : , : , :1])
print(a[: , ::2 , 1:3])

[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [19]
  [23]]]
[[[ 2  3]
  [10 11]]

 [[14 15]
  [24 25]]]


In [4]:
print(a[: , : , ::2])

[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[13 15]
  [19 21]
  [23 25]]]


In [5]:
print(a[ : , ::2, ::2])

[[[ 1  3]
  [ 9 11]]

 [[13 15]
  [23 25]]]


In [6]:
print(a[1:, 1:, :1])

[[[19]
  [23]]]
